##### Prefix / keys #####

# Screen-like prefix
set -g prefix C-a
unbind C-b

# Fast switch between last 2 windows
bind-key C-a last-window

# Default termtype
set -g default-terminal "screen-256color"

# xterm keys
set -g xterm-keys on

# Watch for activity in background windows
setw -g monitor-activity off

# scrollback size
set -g history-limit 10000

# start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Convenience binds
bind-key C-d detach-client
bind-key C-c new-window
bind-key C-p paste-buffer

# Redraw the client (if interrupted by wall, etc)
bind r refresh-client \; display 'Refreshed.'

# Reload tmux config
unbind R
bind R source-file ~/.tmux.conf \; display 'Reloaded tmux config.'


##### Mouse #####
set -g mouse off


##### Colors #####
COL=colour64

# Pane border colours
set -g pane-border-style "fg=$COL"
set -g pane-active-border-style "fg=$COL"

# Status bar colours
set -g status-style "fg=black,bg=$COL"

# Window status colours
set -g window-status-style "fg=black,bg=$COL"
set -g window-status-current-style "fg=$COL,bg=black"
